# Generated by Django 3.1.3 on 2020-11-06 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('raterapi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playergame',
            name='review',
        ),
    ]
